all: OM.dll SIM.dll
	# Comment here preserves the prior tab
OM.dll: OM.cpp
	Rscript --vanilla -e "TMB::compile('OM.cpp','-march=native -O2 -std=gnu++11')"
SIM.dll: SIM.cpp
	Rscript --vanilla -e "TMB::compile('SIM.cpp','-march=native -O2 -std=gnu++11')"

clean:
	rm -rf *o 
